SELECT F.ORDER_ID,F.PRODUCT_ID,DATE_FORMAT(F.OUT_DATE,'%Y-%m-%d') AS OUT_DATE,T1.OUT_YN AS '출고여부'
FROM (SELECT ORDER_ID,
CASE WHEN OUT_DATE IS NULL THEN '출고미정'
WHEN DATE_FORMAT(OUT_DATE,"%Y%m%d")<=20220501 THEN '출고완료'
ELSE '출고대기' END AS OUT_YN
FROM FOOD_ORDER)T1 INNER JOIN FOOD_ORDER F ON T1.ORDER_ID = F.ORDER_ID
ORDER BY 1