SELECT AI.ANIMAL_ID,AI.NAME
FROM (SELECT ANIMAL_ID,DATETIME
FROM ANIMAL_OUTS)AO INNER JOIN ANIMAL_INS AI ON AI.ANIMAL_ID = AO.ANIMAL_ID
WHERE DATEDIFF(AO.DATETIME,AI.DATETIME)>0
ORDER BY DATEDIFF(AO.DATETIME,AI.DATETIME) DESC
LIMIT 2