-- 코드를 입력하세요
SELECT *
FROM (SELECT C.CAR_ID,C.CAR_TYPE,ROUND(C.DAILY_FEE*(100-D.DISCOUNT_RATE)/100,0)*30 AS FEE
      FROM CAR_RENTAL_COMPANY_CAR C INNER JOIN (SELECT CAR_TYPE,DISCOUNT_RATE
                                          FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
                                          WHERE DURATION_TYPE LIKE '30%') D
                                          ON C.CAR_TYPE = D.CAR_TYPE
WHERE C.CAR_TYPE IN ('SUV','세단')
AND C.CAR_ID NOT IN (SELECT DISTINCT CAR_ID
               FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
               WHERE '2022-11' BETWEEN SUBSTR(START_DATE,1,7) AND SUBSTR(END_DATE,1,7)
               ORDER BY CAR_ID))E
WHERE E.FEE BETWEEN 500000 AND 2000000

ORDER BY E.FEE DESC, E.CAR_TYPE , E.CAR_ID DESC