-- 코드를 입력하세요
SELECT I.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES,ADDRESS,ROUND(AVG(REVIEW_SCORE),2) AS SCORE
FROM (SELECT REST_ID,REVIEW_SCORE
from REST_REVIEW) R INNER JOIN REST_INFO I ON R.REST_ID = I.REST_ID
WHERE I.ADDRESS LIKE '서울%'
GROUP BY 1
ORDER BY 6 DESC,FAVORITES DESC
