-- 코드를 입력하세요
SELECT YEAR(SALES_DATE) AS YEAR,MONTH(SALES_DATE) AS MONTH,GENDER, COUNT(DISTINCT U.USER_ID) AS USERS
FROM (SELECT USER_ID,GENDER
FROM USER_INFO
WHERE GENDER IS NOT NULL) U INNER JOIN ONLINE_SALE S ON U.USER_ID = S.USER_ID
GROUP BY 1,2,3
ORDER BY 1,2,3