SELECT UT.USER_ID,UT.NICKNAME,SUM(BT.PRICE) AS TOTAL_SALES
FROM (SELECT WRITER_ID,PRICE
FROM USED_GOODS_BOARD
WHERE STATUS = 'DONE')BT INNER JOIN USED_GOODS_USER UT ON BT.WRITER_ID = UT.USER_ID
GROUP BY 1
HAVING SUM(BT.PRICE)>=700000
ORDER BY 3