-- 코드를 입력하세요
SELECT MONTH(START_DATE) AS MONTH ,CAR_ID,COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE start_date>="2022-08-01" and start_date<"2022-11-01"
AND CAR_ID IN(SELECT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE start_date>="2022-08-01" and start_date<"2022-11-01"
GROUP BY 1
HAVING COUNT(*)>=5)
GROUP BY 1,2
HAVING COUNT(*)>0
ORDER BY MONTH,CAR_ID DESC