-- 코드를 입력하세요
SELECT U.TITLE,U.BOARD_ID,R.REPLY_ID,R.WRITER_ID,R.CONTENTS,DATE_FORMAT(R.CREATED_DATE,'%Y-%m-%d') as CREATED_DATE
FROM USED_GOODS_BOARD U INNER JOIN USED_GOODS_REPLY R ON U.BOARD_ID = R.BOARD_ID
WHERE U.CREATED_DATE LIKE '2022-10%'
ORDER BY 6,1